"""Shared timeout and retry configuration."""

from __future__ import annotations

import os

DB_CLUSTER_WAIT_TIMEOUT = int(os.environ.get("DB_CLUSTER_WAIT_TIMEOUT", "1200"))
DB_INSTANCE_DELETE_TIMEOUT = int(os.environ.get("DB_INSTANCE_DELETE_TIMEOUT", "1200"))
POD_READY_WAIT_TIMEOUT = int(os.environ.get("POD_READY_WAIT_TIMEOUT", "600"))
STATUS_CHECK_INTERVAL = int(os.environ.get("STATUS_CHECK_INTERVAL", "30"))
VERIFICATION_TIMEOUT = int(os.environ.get("VERIFICATION_TIMEOUT", "300"))
VERIFICATION_INTERVAL = int(os.environ.get("VERIFICATION_INTERVAL", "10"))
VERIFICATION_MAX_ATTEMPTS = int(os.environ.get("VERIFICATION_MAX_ATTEMPTS", "6"))
DATA_RESTORE_JOB_TIMEOUT = int(os.environ.get("TEMP_POD_COMPLETION_TIMEOUT", "600"))
DEFAULT_OPENEMR_VERSION = "8.2.0"
PASSWORD_RESET_MAX_ATTEMPTS = 3
PASSWORD_RESET_RETRY_DELAY = 5.0
