apiVersion: batch/v1
kind: Job
metadata:
  name: warp-ccda-upload-benchmark
  namespace: openemr
  labels:
    app: warp
    command: ccda-data-upload
    benchmark: "true"
spec:
  # Retry policy
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600  # Clean up after 1 hour
  
  template:
    metadata:
      labels:
        app: warp
        command: ccda-data-upload
        benchmark: "true"
    spec:
      serviceAccountName: openemr-sa  # Use OpenEMR service account for IRSA
      restartPolicy: Never
      
      containers:
      - name: warp
        # Python image version: Uses latest 3.xx-slim tag automatically
        # Version is managed in versions.yaml under applications.python
        image: python:3.14-slim
        workingDir: /app
        
        env:
        # Database connection (from Kubernetes secrets)
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-database
        
        # Data source configuration - Full dataset benchmark
        - name: DATA_SOURCE
          value: "s3://synpuf-omop/cmsdesynpuf1k/"
        - name: AWS_REGION
          value: "us-west-2"
        
        # Processing options - Full dataset import (no MAX_RECORDS limit)
        - name: BATCH_SIZE
          value: "100"  # Larger batch size for better performance
        - name: WORKERS
          value: "4"    # More workers for parallel processing
        # Note: MAX_RECORDS not set - imports entire dataset
        
        # Logging
        - name: LOG_LEVEL
          value: "INFO"
        
        command: ["/bin/bash"]
        args:
        - -c
        - |
          set -e
          echo "=========================================="
          echo "Warp Full Dataset Import Benchmark"
          echo "=========================================="
          echo "Start time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          START_TIME=$(date +%s)
          
          echo "Installing system dependencies..."
          apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
          
          echo "Installing Python dependencies..."
          # Versions pinned to match versions.yaml
          pip install --no-cache-dir pymysql==1.1.0 boto3==1.28.0
          
          echo "Extracting warp code from ConfigMap..."
          cd /app
          tar xzf /warp-code/warp-code.tar.gz
          
          echo "Installing warp..."
          cd /app
          pip install --no-cache-dir -e .
          
          echo "Running warp full dataset import..."
          warp ccda_data_upload \
            --db-host "$DB_HOST" \
            --db-user "$DB_USER" \
            --db-password "$DB_PASSWORD" \
            --db-name "$DB_NAME" \
            --data-source "$DATA_SOURCE" \
            --batch-size "$BATCH_SIZE" \
            --workers "$WORKERS" \
            --aws-region "$AWS_REGION"
          
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "=========================================="
          echo "Benchmark Complete"
          echo "End time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "Total duration: ${DURATION} seconds ($(echo "scale=2; $DURATION / 60" | bc) minutes)"
          echo "=========================================="
        
        # Resources - Increased for benchmark performance
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        
        # Volume mounts
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: warp-code
          mountPath: /warp-code
          readOnly: true
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: warp-code
        configMap:
          name: warp-code
      
      # Use IRSA for S3 access
      # The service account should have S3 read permissions