apiVersion: batch/v1
kind: Job
metadata:
  name: warp-ccda-upload-test
  namespace: openemr
  labels:
    app: warp
    command: ccda-data-upload
spec:
  # Retry policy
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600  # Clean up after 1 hour
  
  template:
    metadata:
      labels:
        app: warp
        command: ccda-data-upload
    spec:
      serviceAccountName: openemr-sa  # Use OpenEMR service account for IRSA
      restartPolicy: Never
      
      containers:
      - name: warp
        # Python image version: Uses latest 3.xx-slim tag automatically
        # Version is managed in versions.yaml under applications.python
        # To use a specific version, replace with: python:3.14-slim
        image: python:3.14-slim
        workingDir: /app
        
        env:
        # Database connection (from Kubernetes secrets)
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: openemr-db-credentials
              key: mysql-database
        
        # Data source configuration
        - name: DATA_SOURCE
          value: "s3://synpuf-omop/cmsdesynpuf1k/"
        - name: DATASET_SIZE
          value: "1k"
        - name: AWS_REGION
          value: "us-west-2"
        
        # Processing options - benchmark test (full dataset, single worker for stability)
        - name: BATCH_SIZE
          value: "100"  # Larger batch for better performance
        - name: WORKERS
          value: "1"  # Single worker to avoid DB connection issues
        # Note: MAX_RECORDS not set - imports entire dataset
        
        # Logging
        - name: LOG_LEVEL
          value: "INFO"
        
        command: ["/bin/bash"]
        args:
        - -c
        - |
          set -e
          echo "Installing system dependencies..."
          apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
          
          echo "Installing Python dependencies..."
          # Versions pinned to match versions.yaml
          pip install --no-cache-dir pymysql==1.1.0 boto3==1.28.0
          
          echo "Extracting warp code from ConfigMap..."
          cd /app
          tar xzf /warp-code/warp-code.tar.gz
          
          echo "Checking extracted structure..."
          ls -la /app/ | head -15
          
          echo "Installing warp..."
          # The tarball extracts to /app/ with setup.py at root and warp/ subdirectory
          cd /app
          pip install --no-cache-dir -e .
          
          echo "Running warp..."
          WARP_CMD="warp ccda_data_upload \
            --db-host \"$DB_HOST\" \
            --db-user \"$DB_USER\" \
            --db-password \"$DB_PASSWORD\" \
            --db-name \"$DB_NAME\" \
            --data-source \"$DATA_SOURCE\" \
            --dataset-size \"$DATASET_SIZE\" \
            --batch-size \"$BATCH_SIZE\" \
            --workers \"$WORKERS\" \
            --aws-region \"$AWS_REGION\""
          
          # Add --max-records only if MAX_RECORDS is set and not empty
          if [ -n "${MAX_RECORDS:-}" ]; then
            WARP_CMD="$WARP_CMD --max-records \"$MAX_RECORDS\""
          fi
          
          eval $WARP_CMD
        
        # Resources
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        
        # Volume mounts
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: warp-code
          mountPath: /warp-code
          readOnly: true
        
      volumes:
      - name: tmp
        emptyDir: {}
      - name: warp-code
        configMap:
          name: warp-code
      
      # Use IRSA for S3 access (if configured)
      # The service account should have S3 read permissions

